name: ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2          # Untuk API calls
  provider: ^6.1.1      # Untuk state management

  flutter_bloc: ^9.1.1      # Untuk testing bloc
  equatable: ^2.0.5          # Untuk membandingkan objek dalam bloc


  shared_preferences: ^2.2.2  # Untuk menyimpan data lokal
  sqflite: ^2.3.0            # Untuk database lokal SQLite
  path: ^1.8.3               # Untuk manipulasi path file


  google_fonts: ^6.1.0        # Untuk menggunakan font Google

  intl: ^0.18.1               # Untuk internasionalisasi dan format tanggal


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true